project/tasks/forms.py
from flask_wtf import Form
from wtforms import StringField, DateField, IntegerField, SelectField
from wtforms.validators import DataRequired

class AddTaskForm(Form):
    task_id = IntegerField()
    name = StringField('Task Name', validators=[DataRequired()])
    due_date = DateField(
        'Date Due (dd/mm/yyyy)',
        validators=[DataRequired()], format='%d/%m/%Y'
    )
    priority = SelectField(
        'Priority',
        validators=[DataRequired()],
        choices=[
            ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'),
            ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')
        ]
    )
status = IntegerField('Status')

project/tasks/views.py
import datetime
from functools import wraps
from flask import flash, redirect, render_template, request, session, url_for, Blueprint

from .forms import AddTaskForm
from project import db
from project.models import Task


################
#### config ####
################
# init this blueprint
tasks_blueprint = Blueprint('tasks', __name__)


##########################
#### helper functions ####
##########################
def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap

def open_tasks():
    return db.session.query(Task).filter_by(
        status='1').order_by(Task.due_date.asc())


def closed_tasks():
    return db.session.query(Task).filter_by(
        status='0').order_by(Task.due_date.asc())


################
#### routes ####
################
#bound every route handle to the blueprint
@tasks_blueprint.route('/tasks/')
@login_required
def tasks():
    return render_template(
        'tasks.html',
        form=AddTaskForm(request.form),
        open_tasks=open_tasks(),
        closed_tasks=closed_tasks(),
        username=session['name']
    )


@tasks_blueprint.route('/add/', methods=['GET', 'POST'])
@login_required
def new_task():
    error = None
    form = AddTaskForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_task = Task(
                form.name.data,
                form.due_date.data,
                form.priority.data,
                datetime.datetime.utcnow(),
                '1',
                session['user_id']
            )
            db.session.add(new_task)
            db.session.commit()
            flash('New entry was successfully posted. Thanks.')
            return redirect(url_for('tasks.tasks'))
    return render_template(
        'tasks.html',
        form=form,
        error=error,
        open_tasks=open_tasks(),
        closed_tasks=closed_tasks()
    )


@tasks_blueprint.route('/complete/<int:task_id>/')
@login_required
def complete(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.update({"status": "0"})
        db.session.commit()
        flash('The task is complete. Nice.')
        return redirect(url_for('tasks.tasks'))
    else:
        flash('You can only update tasks that belong to you.')
        return redirect(url_for('tasks.tasks'))


@tasks_blueprint.route('/delete/<int:task_id>/')
@login_required
def delete_entry(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.delete()
        db.session.commit()
        flash('The task was deleted. Why not add a new one?')
        return redirect(url_for('tasks.tasks'))
    else:
        flash('You can only delete tasks that belong to you.')
    return redirect(url_for('tasks.tasks'))

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Welcome to FlaskTaskr!!!</title>
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png') }}" sizes="32x32">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">FlaskTaskr</a>
                    </div>
                    <ul class="nav navbar-nav">
                        {% if not session.logged_in %}
                            <li><a href="/register">Signup</a></li>
                        {% else %}
                            <li><a href="/logout">Signout</a></li>
                        {% endif %}
                    </ul><!--/.nav-collapse -->
                </div>
            </nav>
            <div class="container">
                <div class="content">
                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>

                    {% endfor %}
                    {% if error %}
                        <div class="error"><strong>Error:</strong> {{ error }}</div>
                    {% endif %}
                    {% block content %}
                    <!-- Content goes here -->
                    {% endblock %}
                </div>
                <div class="footer">
                    <hr>
                    <p>&copy; Bartez</p>
                </div>
            </div><!-- /.container -->
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>
</html>

project/templates/login.html
<!DOCTYPE html>
{% extends "_base.html" %}
{% block content %}

    <h1>Welcome to FlaskTaskr.</h1>
    <h3>Please sign in to access your task list</h3>
    <form class="form-signin" role="form" method="post" action="/">
        <!-- Security Token -->
        {{ form.csrf_token }}
        <div class="input-group">
            {{ form.name(placeholder="Username") }}
            {% if form.name.errors %}
                <span class="error">
                    {% for error in form.name.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}
        </div>
        <div class="input-group">
            {{ form.password(placeholder="Password") }}
            {% if form.password.errors %}
                <span class="error">
                    {% for error in form.password.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}
        </div>
        <button class="btn btn-outline-success" type="submit">Sign in</button>
        <br>
        <br>
        <p><em>Need an account? </em><a href="/register">Signup!!</a></p>
    </form>

{% endblock %}

project/templates/register.html
<!DOCTYPE html>
{% extends "_base.html" %}
{% block content %}

    <h1>Welcome to FlaskTaskr.</h1>
    <h3>Please register to access the task list.</h3>
    <form method="POST" action="/register/">
        <!-- Security Token -->
        {{ form.csrf_token }}
        <div class="input-group">
            {{ form.name(placeholder="Username") }}
            {% if form.name.errors %}
                <span class="error">
                    {% for error in form.name.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}
        </div>
        <div class="input-group">
            {{ form.email(placeholder="Email") }}
            {% if form.email.errors %}
                <span class="error">
                    {% for error in form.email.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}
        </div>
        <div class="input-group">
            {{ form.password(placeholder="Password") }}
            {% if form.password.errors %}
                <span class="error">
                    {% for error in form.password.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}
        </div>
        <div class="input-group">
            {{ form.confirm(placeholder="Confirm Password") }}
            {% if form.confirm.errors %}
                <span class="error">
                    {% for error in form.confirm.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
            {% endif %}
        </div>
        <button class="btn btn-outline-success" type="submit">Register</button>
        <br>
        <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
    </form>

{% endblock %}

project/templates/tasks.html
<!doctype html>
{% extends "_base.html" %}
{% block content %}


{% if session.logged_in %}
<div class="row">
    <div class="col-md-10">
        <h1>Welcome to FlaskTaskr</h1>
    </div>
    <div class="col-md-2" style="text-align:right">
        Welcome, {{username}}
    </div>
</div>
{% endif %}
<br>
<div class="add-task">
  <h3>Add a new task:</h3>
    <form action="{{ url_for('tasks.new_task') }}" method="post">
        <!-- security token -->
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.name(placeholder="Task") }}
        {% if form.name.errors %}
          <span class="error">
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.due_date(placeholder="Due Date (dd/mm/yyyy)") }}
        {% if form.due_date.errors %}
          <span class="error">
            {% for error in form.due_date.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.priority.label }}
        {{ form.priority }}
        {% if form.priority.errors %}
          <span class="error">
            {% for error in form.priority.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
      </div>
      <div class="form-group"><input class="btn btn-outline-success" type="submit" value="Submit"></div>
    </form>
</div>
<div class="entries">
  <br>
  <br>
  <h2>Open tasks:</h2>
  <div class="datagrid">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th width="200px"><strong>Task Name</strong></th>
          <th width="75px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="90px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in open_tasks %}
        <tr>
          <td width="200px">{{ task.name }}</td>
          <td width="75px">{{ task.due_date }}</td>
          <td width="100px">{{ task.posted_date }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="90px">{{ task.poster.name }}</td>
          <td>
            {% if task.poster.name == session.name or session.role == "admin" %}
              <a href="{{ url_for('tasks.delete_entry', task_id = task.task_id) }}">Delete</a>  -
              <a href="{{ url_for('tasks.complete', task_id = task.task_id) }}">Mark as Complete</a>
            {% else %}
              <span>N/A</span>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
<br>
<br>
<div class="entries">
  <h2>Closed tasks:</h2>
  <div class="datagrid">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th width="200px"><strong>Task Name</strong></th>
          <th width="75px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="90px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in closed_tasks %}
        <tr>
          <td width="200px">{{ task.name }}</td>
          <td width="75px">{{ task.due_date }}</td>
          <td width="100px">{{ task.posted_date }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="90px">{{ task.poster.name }}</td>
          <td>
             {% if task.poster.name == session.name or session.role == "admin" %}
                <a href="{{ url_for('tasks.delete_entry', task_id = task.task_id) }}">Delete</a>
             {% else %}
               <span>N/A</span>
             {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}